name: CI/CD Backend

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
    paths:
      - 'template.yaml'  # Trigger when the SAM template changes
      - 'src/**'  # Trigger when changes occur in your source code
      - 'tests/**'  # Trigger when changes occur in the tests folder

jobs:
  # Job to install dependencies
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Install pytest for running tests

  # Job to run Python tests
  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Run Python tests
        run: |
          pytest tests/  # Runs tests located in the 'tests' folder

  # Job to deploy SAM application
  deploy_sam:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Package and Deploy SAM Application
        run: |
          sam build
          sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM
